#!/bin/bash

sudo rm -rf protected/data/f/*
sudo rm -rf assets/*
sudo chmod 777 protected/data/f

cat protected/data/schema.mysql.sql | mysql -u root -p fapp

if [ "$HOSTNAME" = "ub" ]; then
    git-changelog > changelog.log
fi
